name: VirtualFilter
version: 1.8.1
main: com.comonier.virtualfilter.VirtualFilter
api-version: 1.21
depend: [Vault]

commands:
  abf:
    description: Opens the AutoBlock menu.
  isf:
    description: Opens the InfinityStack menu.
  asf:
    description: Opens the AutoSell menu.
  isfe:
    description: Opens the InfinityStack Edit (Edited Items) menu.
  addabf:
    description: Adds the item in hand to AutoBlock.
  addisf:
    description: Adds the item in hand to InfinityStack.
  addasf:
    description: Adds the item in hand to AutoSell.
  addisfe:
    description: Adds the edited item in hand to InfinityStack Edit.
  remabf:
    description: Removes a filter from AutoBlock by hand or slot ID.
    aliases: [rabf]
  remisf:
    description: Removes a filter from InfinityStack by hand or slot ID.
    aliases: [risf]
  remasf:
    description: Removes a filter from AutoSell by hand or slot ID.
    aliases: [rasf]
  remisfe:
    description: Removes an edited filter from ISFE by hand or slot ID.
    aliases: [risfe]
  getisf:
    description: Withdraws items from your ISF storage by slot ID.
    aliases: [sacar, isg]
  getisfe:
    description: Withdraws items from your ISFE storage by slot ID.
    aliases: [sacaredit]
  al:
    description: Enables/Disables AutoLoot.
  afh:
    description: Enables/Disables AutoFillHand (ISF search).
  lo:
    description: Enables/Disables viewing your own loot logs.
    aliases: [vflogsown]
  la:
    description: Enables/Disables viewing loot logs from nearby players.
    aliases: [vflogsall]
  vfat:
    description: Toggles notifications in the Action Bar.
  sd:
    description: Toggles the 10-second protection for dropped items.
    aliases: [safedrop]
  vflang:
    description: Changes personal language (en/pt).
  vfhelp:
    description: Shows the help menu.
    aliases: [vf, vfilter]
  vfreload:
    description: Reloads the configuration files.
    permission: virtualfilter.admin
    permission-message: §cNo permission.

permissions:
  virtualfilter.admin:
    description: Permission to use the plugin reload command.
    default: op
