name: VirtualFilter
version: 1.3.3
main: com.comonier.virtualfilter.VirtualFilter
api-version: 1.21
author: comonier
description: Professional Independent Virtual Filtering System.

commands:
  abf:
    description: Opens the AutoBlockFilter menu.
  addabf:
    description: Adds the item in hand to the first free ABF slot.
  isf:
    description: Opens the InfinityStackFilter menu.
  addisf:
    description: Adds the item in hand to the first free ISF slot.
  asf:
    description: Opens the AutoSellFilter menu.
  addasf:
    description: Adds the item in hand to the first free ASF slot.
  vfat:
    description: Toggle AutoSell Action Bar notifications.
  vflang:
    description: Changes personal language (en/pt).
  vfhelp:
    description: Shows all commands and features.
    aliases: [vf, vfilter]
  vfreload:
    description: Reloads plugin configurations and prices.
    permission: virtualfilter.admin
  afh:
    description: Toggle the AutoFillHand feature.
  al:
    description: Toggle the AutoLoot feature.

permissions:
  virtualfilter.use:
    default: true
  virtualfilter.admin:
    default: op
