name: VirtualFilter
version: 1.4
main: com.comonier.virtualfilter.VirtualFilter
api-version: 1.21
depend: [Vault]
softdepend: [ShopGUIPlus]
commands:
  abf:
    description: Opens the AutoBlock filter menu.
  isf:
    description: Opens the InfinityStack virtual storage menu.
  asf:
    description: Opens the AutoSell filter menu.
  addabf:
    description: Add held item to AutoBlock.
  addisf:
    description: Add held item to InfinityStack.
  addasf:
    description: Add held item to AutoSell.
  remabf:
    description: Remove held item from AutoBlock.
  remisf:
    description: Remove held item from InfinityStack.
  remasf:
    description: Remove held item from AutoSell.
  isg:
    description: Withdraw items from your ISF storage by slot ID.
    aliases: [sacar, getisf]
  al:
    description: Toggle AutoLoot.
  afh:
    description: Toggle AutoFillHand.
  vfat:
    description: Toggle Action Bar notifications.
  vflang:
    description: Change personal language.
  vfhelp:
    description: Shows all commands and features.
    aliases: [vf, vfilter]
  vfreload:
    description: Reload configurations and prices.
    permission: virtualfilter.admin
