name: VirtualFilter
version: 1.7.9
main: com.comonier.virtualfilter.VirtualFilter
api-version: 1.21
depend: [Vault]
softdepend: [ShopGUIPlus]

commands:
  abf:
    description: Abre o menu do AutoBlock.
  isf:
    description: Abre o menu do InfinityStack.
  asf:
    description: Abre o menu do AutoSell.
  isfe:
    description: Abre o menu do InfinityStack Edit (Itens Editados).
  addabf:
    description: Adiciona o item da mao ao AutoBlock.
  addisf:
    description: Adiciona o item da mao ao InfinityStack.
  addasf:
    description: Adiciona o item da mao ao AutoSell.
  addisfe:
    description: Adiciona o item editado da mao ao InfinityStack Edit.
  remabf:
    description: Remove o item da mao ou por slot do AutoBlock.
    aliases: [rabf]
  remisf:
    description: Remove o item da mao ou por slot do InfinityStack.
    aliases: [risf]
  remasf:
    description: Remove o item da mao ou por slot do AutoSell.
    aliases: [rasf]
  remisfe:
    description: Remove o item editado da mao ou por slot do ISFE.
    aliases: [risfe]
  getisf:
    description: Saca itens do seu estoque ISF por ID do slot.
    aliases: [sacar, getisf, isg]
  getisfe:
    description: Saca itens do seu estoque ISFE por ID do slot.
    aliases: [sacaredit]
  al:
    description: Ativa/Desativa o AutoLoot.
  afh:
    description: Ativa/Desativa o AutoFillHand (Busca no ISF).
  lo:
    description: Ativa/Desativa a visualizacao das suas proprias logs de loot.
    aliases: [vflogsown]
  la:
    description: Ativa/Desativa a visualizacao das logs de loot de outros jogadores proximos.
    aliases: [vflogsall]
  vfat:
    description: Alterna avisos na Action Bar.
  sd:
    description: Alterna a protecao de 10 segundos para itens jogados no chao.
    aliases: [safedrop]
  vflang:
    description: Altera o idioma pessoal (en/pt).
  vfhelp:
    description: Mostra o menu de ajuda.
    aliases: [vf, vfilter]
  vfreload:
    description: Recarrega as configuracoes.
    permission: virtualfilter.admin
    permission-message: §cSem permissao.

permissions:
  virtualfilter.admin:
    description: Permissao para usar o reload do plugin.
    default: op
