name: VirtualFilter
version: 1.5
main: com.comonier.virtualfilter.VirtualFilter
api-version: 1.21
depend: [Vault]
softdepend: [ShopGUIPlus]

commands:
  abf:
    description: Abre o menu do AutoBlock.
  isf:
    description: Abre o menu do InfinityStack.
  asf:
    description: Abre o menu do AutoSell.
  addabf:
    description: Adiciona o item da mão ao AutoBlock.
  addisf:
    description: Adiciona o item da mão ao InfinityStack.
  addasf:
    description: Adiciona o item da mão ao AutoSell.
  remabf:
    description: Remove o item da mão ou por slot do AutoBlock.
    aliases: [rabf]
  remisf:
    description: Remove o item da mão ou por slot do InfinityStack.
    aliases: [risf]
  remasf:
    description: Remove o item da mão ou por slot do AutoSell.
    aliases: [rasf]
  isg:
    description: Saca itens do seu estoque ISF por ID do slot.
    aliases: [sacar, getisf]
  al:
    description: Ativa/Desativa o AutoLoot.
  afh:
    description: Ativa/Desativa o AutoFillHand (Busca no ISF).
  vfcb:
    description: Ativa/Desativa o relatório de quebra de baús.
    aliases: [chestdebug]
  vfat:
    description: Alterna avisos na Action Bar.
  vflang:
    description: Altera o idioma pessoal (en/pt).
  vfhelp:
    description: Mostra o menu de ajuda.
    aliases: [vf, vfilter]
  vfreload:
    description: Recarrega as configurações.
    permission: virtualfilter.admin
    permission-message: §cSem permissão.

permissions:
  virtualfilter.admin:
    description: Permissao para usar o reload do plugin.
    default: op
  virtualfilter.chestdebug:
    description: Permissao para ver o relatorio de baus.
    default: true
